packages:
  - "docs/*"
  - "packages/*"
  - "configs/*"

catalog:
  "@types/node": "22.14.1"
  "plop": "4.0.1"
  "typescript": "5.8.3"
  "tsup": "8.4.0"
  "vite": "6.2.6"
  "vitest": "3.1.1"
  "vite-tsconfig-paths": "5.1.4"
  "happy-dom": "17.4.4"
  "vitest-fetch-mock": "0.2.2"
  "@testing-library/jest-dom": "6.6.3"
  "@testing-library/react": "16.3.0"
  "@testing-library/user-event": "14.6.1"
  "@vitejs/plugin-react": "4.3.4"
  "@vitest/coverage-v8": "3.1.1"

catalogs:
  react18:
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "@types/react": "^18.3.12"
    "@types/react-dom": "^18.3.1"
    "react-native": "^0.76.1"

  react19:
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@types/react": "^18.3.12"
    "@types/react-dom": "^18.3.1"
